apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: svksounds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vilimantas/lab.git
    targetRevision: main
    path: aks-terraform/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: svksounds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true